import type { Metadata } from "next";
import { Footer, Header } from "../site";

export const metadata: Metadata = {
  title: "Privacy Policy | i8is",
  description: "Learn how i8is collects, uses, protects and manages personal information across its website, products, services and recruitment activities.",
  alternates: { canonical: "https://i8is.com/privacy/" },
};

export default function PrivacyPage() {
  return <><Header /><main><section className="legalHero"><div className="kicker">Legal</div><h1>Privacy Policy</h1><p>Effective date: <strong>September 14, 2026</strong></p></section><div className="legalShell" style={{ display: "block", width: "100%" }}><article className="legalContent" style={{ width: "100%" }}>
    <p className="legalIntro">i8is Inc. respects your privacy.</p><p>This Privacy Policy explains how we collect, use, protect and disclose personal information when you visit i8is.com, contact us, apply for a role, use our digital products or engage us for technology, workforce or consulting services.</p><p>This Policy applies to information collected through our website and through communications or forms connected to the website.</p>
    <h2>1. Information we collect</h2><p>We may collect information that you provide directly to us, including:</p><ul><li>Your name</li><li>Work email address</li><li>Telephone number</li><li>Organization name</li><li>Country or region</li><li>Area of interest</li><li>Project information</li><li>Career information</li><li>Resume or professional profile information</li><li>Information included in messages or inquiries</li></ul><p>We may also collect limited technical information when you use our website, such as:</p><ul><li>IP address</li><li>Browser type</li><li>Device type</li><li>Operating system</li><li>Pages viewed</li><li>Referring website</li><li>Approximate usage information</li><li>Date and time of access</li></ul>
    <h2>2. How we use information</h2><p>We may use information to:</p><ul><li>Respond to inquiries</li><li>Communicate about requested services</li><li>Evaluate recruitment applications</li><li>Maintain and improve our website</li><li>Improve products and services</li><li>Understand website usage</li><li>Protect website security</li><li>Prevent fraud or misuse</li><li>Meet legal and contractual obligations</li><li>Maintain business records</li><li>Manage business relationships</li></ul><p>We will not use personal information for purposes that are materially incompatible with the purpose for which it was collected unless permitted or required by law.</p>
    <h2>3. Careers information</h2><p>If you submit information through our careers or talent-network form, we may use that information to:</p><ul><li>Review your experience</li><li>Evaluate current or future opportunities</li><li>Contact you about relevant roles</li><li>Maintain recruitment records</li><li>Communicate about the hiring process</li></ul><p>Please do not submit information that is unnecessary for recruitment or information belonging to another person without permission.</p>
    <h2>4. Client and project information</h2><p>If you contact us about a project, please do not submit passwords, payment information, confidential client materials, security credentials or sensitive personal information through a general website form.</p><p>Project information may be handled under additional contractual terms, confidentiality agreements or data-processing arrangements.</p>
    <h2>5. Cookies and analytics</h2><p>Our website may use cookies or similar technologies to support essential functionality, understand website usage and improve the user experience.</p><p>Where required, we will request consent before using non-essential cookies or analytics technologies.</p><p>You may be able to control cookies through your browser settings. Disabling certain cookies may affect website functionality.</p><div className="legalReview">Insert the exact analytics and cookie providers used by the website.</div>
    <h2>6. How we share information</h2><p>We may share information with:</p><ul><li>Service providers that support website hosting, communications, analytics or security</li><li>Professional advisers</li><li>Technology providers</li><li>Government authorities or regulators where required by law</li><li>A successor organization in connection with a merger, acquisition or business transfer</li></ul><p>We do not sell personal information for money.</p><div className="legalReview">Confirm whether i8is uses advertising, retargeting or data-sharing services.</div>
    <h2>7. International transfers</h2><p>i8is operates across multiple regions. Personal information may be accessed, processed or stored in a country different from the country in which it was collected.</p><p>Where required, we will use appropriate safeguards for international transfers and handle information in accordance with applicable legal requirements.</p>
    <h2>8. Data retention</h2><p>We retain personal information only for as long as reasonably necessary for the purposes described in this Policy, including responding to inquiries, managing recruitment, maintaining business records, resolving disputes and meeting legal obligations.</p><p>Retention periods may vary depending on the type of information and the reason it was collected.</p>
    <h2>9. Security</h2><p>We use reasonable administrative, technical and organizational safeguards designed to protect personal information against unauthorized access, loss, misuse, alteration or disclosure.</p><p>No method of transmission or storage is completely secure. We cannot guarantee absolute security.</p>
    <h2>10. Your privacy rights</h2><p>Depending on where you live, you may have rights relating to your personal information, including the right to:</p><ul><li>Request access</li><li>Request correction</li><li>Request deletion</li><li>Request information about how data is used</li><li>Withdraw consent where processing relies on consent</li><li>Object to certain processing</li><li>Request data portability</li><li>Make a complaint to a privacy regulator</li></ul><p>To exercise applicable rights, contact <a href="mailto:contact@i8is.com">contact@i8is.com</a>. We may need to verify your identity before completing a request.</p>
    <h2>11. Children’s privacy</h2><p>Our website is not directed to children, and we do not knowingly collect personal information from children through the website.</p><p>If you believe a child has provided personal information, contact us so we can review and take appropriate action.</p>
    <h2>12. Third-party websites</h2><p>Our website may contain links to third-party websites or services. We are not responsible for the privacy practices, content or security of third-party websites. We encourage you to review their privacy policies before providing information.</p>
    <h2>13. Changes to this Policy</h2><p>We may update this Privacy Policy from time to time. When we make changes, we will update the effective date at the top of this page. Material changes may be communicated through the website or another appropriate channel.</p>
    <h2>14. Contact us</h2><p>Questions about this Privacy Policy or your personal information can be directed to:</p><address><strong>i8is Inc.</strong><br/>Email: <a href="mailto:contact@i8is.com">contact@i8is.com</a><br/>Phone: <a href="tel:+16479300988">+1 647 930 0988</a><br/>Address: <strong>[Insert approved legal address]</strong></address>
  </article></div></main><Footer /></>;
}
