import type { Metadata } from "next";
import { Footer, Header } from "../site";

export const metadata: Metadata = {
  title: "Terms of Use | i8is",
  description: "Read the terms governing access to and use of the i8is website, including intellectual property, third-party links, disclaimers and limitations of liability.",
  alternates: { canonical: "https://i8is.com/terms/" },
};

export default function TermsPage() {
  return <><Header /><main><section className="legalHero"><div className="kicker">Legal</div><h1>Terms of Use</h1><p>Effective date: <strong>September 14, 2026</strong></p></section><div className="legalShell" style={{ display: "block", width: "100%" }}><article className="legalContent" style={{ width: "100%" }}>
    <p className="legalIntro">These Terms of Use govern your access to and use of i8is.com.</p><p>By using this website, you agree to comply with these Terms. If you do not agree with these Terms, please do not use the website.</p><p>These Terms apply to the website only. Separate written agreements may apply to i8is products, services, employment, consulting, technology delivery or other business relationships.</p>
    <h2 id="website-use">1. Website use</h2><p>You may use this website for lawful, informational and business purposes.</p><p>You agree not to:</p><ul><li>Use the website unlawfully</li><li>Attempt to gain unauthorized access</li><li>Interfere with website security or operation</li><li>Introduce malicious code</li><li>Scrape or copy content in a way that harms the website</li><li>Misrepresent your identity or affiliation</li><li>Use the website to transmit harmful or unlawful material</li><li>Use website content to infringe another person’s rights</li></ul>
    <h2>2. Website content</h2><p>The content on this website is provided for general information.</p><p>We aim to keep the information accurate and current, but we do not guarantee that all content is complete, current, error-free or suitable for every purpose.</p><p>We may change, update, suspend or remove website content at any time.</p>
    <h2>3. No professional advice</h2><p>Website content is provided for general information only.</p><p>It does not create a consulting, employment, technology-support or other professional relationship unless agreed through a separate written contract.</p><p>You should obtain appropriate professional advice before making decisions based on website content.</p>
    <h2 id="intellectual-property">4. Intellectual property</h2><p>Unless otherwise stated, the website and its content—including text, graphics, logos, images, designs, software and layout—are owned by or licensed to i8is.</p><p>You may view and print reasonable portions of the website for personal or internal business use.</p><p>You may not reproduce, modify, distribute, publish, sell, license or create derivative works from website content without prior written permission, except where permitted by law.</p>
    <h2>5. i8is trademarks</h2><p>The i8is name, logo and related marks may be trademarks of i8is or its affiliates. You may not use these marks without prior written permission.</p><p>Product names such as sstrack.io, ClickHR, VerdeBooks and Camel Translator may be owned by i8is or third parties. Their use does not grant you any ownership or license rights.</p>
    <h2>6. User-submitted information</h2><p>If you submit information through the website, you confirm that:</p><ul><li>You have the right to provide the information</li><li>The information is accurate to the best of your knowledge</li><li>The information does not violate another person’s rights</li><li>The information does not contain malicious code</li><li>The information does not include unnecessary confidential or sensitive information</li></ul><p>You should not submit passwords, payment information, security credentials or confidential client material through a general website form.</p>
    <h2>7. Recruitment submissions</h2><p>Information submitted through the careers or talent-network forms may be reviewed for recruitment purposes. Submission of an application does not guarantee an interview, employment or engagement. Employment decisions are subject to applicable law and separate employment documentation.</p>
    <h2>8. Third-party links and services</h2><p>The website may link to third-party websites, platforms or services.</p><p>Third-party links are provided for convenience. i8is does not control and is not responsible for third-party content, availability, security or privacy practices. Your use of third-party services is governed by the applicable third party’s terms and policies.</p>
    <h2>9. Website availability</h2><p>We do not guarantee that the website will always be available, uninterrupted, secure or free from errors. We may suspend or restrict access for maintenance, security, upgrades or other operational reasons.</p>
    <h2 id="disclaimers">10. Disclaimers</h2><p>To the maximum extent permitted by applicable law, the website and its content are provided on an “as is” and “as available” basis.</p><p>i8is disclaims warranties that cannot be excluded by law, including warranties of accuracy, availability, fitness for a particular purpose and non-infringement. Nothing in these Terms limits rights or protections that cannot legally be limited.</p>
    <h2 id="liability">11. Limitation of liability</h2><p>To the maximum extent permitted by applicable law, i8is will not be responsible for indirect, incidental, special, consequential or punitive damages arising from or related to your use of, or inability to use, the website.</p><p>This includes loss of data, revenue, profits, business opportunities or reputation.</p><div className="legalReview">Legal counsel must insert approved liability language and any applicable exclusions.</div>
    <h2>12. Indemnity</h2><p>To the extent permitted by applicable law, you agree to defend, indemnify and hold harmless i8is and its directors, officers, employees, contractors and affiliates from claims, losses, liabilities and expenses arising from:</p><ul><li>Your breach of these Terms</li><li>Your misuse of the website</li><li>Your violation of applicable law</li><li>Your infringement of another person’s rights</li><li>Information you submit to the website</li></ul><div className="legalReview">Legal counsel must review and approve this clause.</div>
    <h2 id="governing-law">13. Governing law and jurisdiction</h2><p>These Terms are governed by the laws of <strong>[Insert approved jurisdiction]</strong>, without regard to conflict-of-law principles.</p><p>The courts located in <strong>[Insert approved jurisdiction]</strong> will have exclusive jurisdiction over disputes arising from or relating to these Terms, unless applicable law requires otherwise.</p><div className="legalReview">This section must be completed by legal counsel.</div>
    <h2>14. Changes to these Terms</h2><p>We may update these Terms from time to time. When we make changes, we will update the effective date at the top of this page. Your continued use of the website after updated Terms are posted means that you accept the updated Terms, to the extent permitted by law.</p>
    <h2>15. Severability</h2><p>If any provision of these Terms is found to be invalid or unenforceable, the remaining provisions will continue to apply.</p>
    <h2>16. Entire agreement</h2><p>These Terms represent the agreement between you and i8is regarding your use of this website, unless a separate written agreement applies.</p>
    <h2 id="contact">17. Contact us</h2><p>Questions about these Terms can be directed to:</p><address><strong>i8is Inc.</strong><br/>Email: <a href="mailto:contact@i8is.com">contact@i8is.com</a><br/>Phone: <a href="tel:+16479300988">+1 647 930 0988</a><br/>Address: <strong>[Insert approved legal address]</strong></address><div className="legalReview">Legal counsel must finalize the entity name, governing law, jurisdiction, liability and indemnity provisions.</div>
  </article></div></main><Footer /></>;
}
